### ISSUE TITLE
Suggestion: Change artifact name

### ISSUE THREAD

**Issue by breadguyyy** [NekuSoul/ShopsOnly#3]
Could be Artifact of choice or something simple but Artifact of Multishop Terminals just doesnt quite roll off the tongue haha.
Btw, format for icons is 512x512, 8x gaussian blur, #e7c7e7 selected, #473e44 deselected :)

Also would it be possible to add a config to increase trishop costs? would just be to balance it out a little lol

**Comment by NekuSoul** [comment]
Changed in v1.0.0
