### ISSUE TITLE
No Artifact Choice

### ISSUE THREAD

**Issue by imakunee** [NekuSoul/ShopsOnly#6]
The mod was working just a day or two ago perfectly. Loving it btw. But I believe one of the dependencies updated and now the artifact no longer shows.

R2API 3.0.13
BepInExPack 5.4.9
HookGenPatcher 1.2.1
ShopsOnly 1.0.0

No other mods

**Comment by NekuSoul** [comment]
Apparently the API for adding artifacts changed again. It's fixed now in 2.0.0.
