### ISSUE TITLE
Artifact Does Nothing

### ISSUE THREAD

**Issue by VaelophisNyx** [NekuSoul/ShopsOnly#7]
Multishops do not replace chests at all, and in fact, I don't think I have seen any at all.

**Comment by NekuSoul** [comment]
Huh, that's pretty weird, it should definitely work again now that I fixed it for the latest update.

Just to double-check:

- Are you running the latest version of the mod? The initial 3.0.0 update was broken and I released 3.0.1 quickly to fix that.
- Is the mod actually shown as active in-game? (Artifact of Options)
- Are you running a bunch of other mods? I've never seen any incompatibility, but just running the bare minimum, which is the mod itself, BepInExPack and HookGen might be helpful.
- Did you play singleplayer or multiplayer? Should work for both, but I've only tested singleplayer with the latest patch.
- Do you own the DLC? Again, shouldn't be a problem either, but who knows.

**Comment by NekuSoul** [comment]
Haven't seen anyone else report similar problems, so I'm closing this for now.
