### ISSUE TITLE
Healing Chest - Large still spawned for me.

### ISSUE THREAD

**Issue by JohnEdwa** [NekuSoul/ShopsOnly#9]
Not that I'm complaining too much as it had a rejuvenation rack.

That level also had three red item shops, was I just really damn lucky, or are the red shops way more common than red items from chests should be? It's not often you have five red items out of 25 at the end of stage 3

**Comment by NekuSoul** [comment]
Thanks for the report. Large category chests still appearing has been fixed in version 3.0.3.
